dependencies:
  # - <organization/repo>@<version>
  # this is the structure for telling 
  #brownie where to get chainlink info
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  #now brownie knowws to download that repository from github
  #since brownie doesnt deal direct with chainlink like remix

  #also need to tell brownie what @chainlink means
  #tell brownie whenever we use @chainlink we actually mean
  #refering to this import from above 
  #done below
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

#wallets and private key stored in .env along with infura project ID
dotenv: .env

networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False    
  Development:
    verify: False
  ganache-local:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
